<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>fdca59b5-1f86-4d1a-96a2-b345fb081be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;தமிழ்&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2270d1bb-c34a-4e20-b352-2f4288d39e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_GHJsWmg4qR9jBjQOLdPzc_InoM8%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiT17qIx4iJAxXrnq8BHSM7FnwQ2ZgBCBs</value>
      <webElementGuid>099f0376-af19-4a98-a299-4001545f802c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>தமிழ்</value>
      <webElementGuid>1df1b78d-b9c0-4857-8254-d5f441212f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[5]</value>
      <webElementGuid>f8cb3122-96c9-45eb-a868-7ee2763ec0a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a[5]</value>
      <webElementGuid>c52e3e70-1f08-42ac-b5fc-41be16e81da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'தமிழ்')]</value>
      <webElementGuid>247795ff-be72-4525-92e7-53b2c6335549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/following::a[1]</value>
      <webElementGuid>038d5951-60f3-4ce2-98d7-824329db1f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='తెలుగు'])[1]/following::a[2]</value>
      <webElementGuid>2713807b-e0bb-4b28-b3b8-4d9898b357e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ગુજરાતી'])[1]/preceding::a[1]</value>
      <webElementGuid>649ae516-69ce-49a0-9b4a-17a81d6a1e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಕನ್ನಡ'])[1]/preceding::a[2]</value>
      <webElementGuid>7c4009c9-e702-4592-b13a-a4c704eebb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='தமிழ்']/parent::*</value>
      <webElementGuid>24da91d6-362a-47f1-9f7f-6a5325e876fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_GHJsWmg4qR9jBjQOLdPzc_InoM8%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiT17qIx4iJAxXrnq8BHSM7FnwQ2ZgBCBs')]</value>
      <webElementGuid>8011b401-2e6e-4ffd-b0d0-8b1dbe511d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>6b5e861e-3538-4187-bf4c-66e1cede729a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_GHJsWmg4qR9jBjQOLdPzc_InoM8%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwiT17qIx4iJAxXrnq8BHSM7FnwQ2ZgBCBs' and (text() = 'தமிழ்' or . = 'தமிழ்')]</value>
      <webElementGuid>cf3a5e00-880b-4bea-a648-89b172ea5146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
