<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>3947bee4-0ebe-43fb-9747-81bed1e5896d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;English&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>105fa462-747c-466e-8508-121acf5c059e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/setprefs?sig=0_GHJsWmg4qR9jBjQOLdPzc_InoM8%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjd_L-Lx4iJAxVTlK8BHXSqNzUQ2ZgBCBU</value>
      <webElementGuid>e6c24f1f-26cd-4265-b3ef-d8f708acc306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>7f34258c-588b-416a-87cf-df6ba3699053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>75f7434a-fc74-4b71-81ab-9203401e81d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>48d9c5c7-c136-47c0-a0d7-cc17af9c1ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>b25d1244-b040-4932-89ab-a8a849aadbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='பொருத்தமற்ற முன்கணிப்புகளைப் புகாரளி'])[1]/following::a[1]</value>
      <webElementGuid>f4997384-237b-4bf4-9399-fbff18751432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='हिन्दी'])[1]/preceding::a[1]</value>
      <webElementGuid>34236df3-3423-4a17-b867-3ffb98a76774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/preceding::a[2]</value>
      <webElementGuid>d534a35e-777e-4633-ac39-b5b9a04942a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>5682d62a-206d-4436-b2d1-d50e231c593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/setprefs?sig=0_GHJsWmg4qR9jBjQOLdPzc_InoM8%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjd_L-Lx4iJAxVTlK8BHXSqNzUQ2ZgBCBU')]</value>
      <webElementGuid>2bd88a1c-339e-499c-8822-772b4045d55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>2f82562e-4538-42a8-87d9-8e42fa273ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/setprefs?sig=0_GHJsWmg4qR9jBjQOLdPzc_InoM8%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjd_L-Lx4iJAxVTlK8BHXSqNzUQ2ZgBCBU' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>81ddb364-5380-4a2a-b52e-57ede5414343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
